# This is a an example of docker-compose for tls-sslwebgateway image
# See https://github.com/lscalese/docker-webgateway-sample 
# and the community article : <NOT PUBLISHED YET - COMING SOON>
# for more details.

version: '3.6'
services:

  webgateway:
    image: tls-ssl-webgateway
    container_name: tls-ssl-webgateway
    networks:
      app_net:
        ipv4_address: 172.16.238.50
    ports:
      # change the local port already used on your system. 
      - "80:80"
      - "443:443"
    environment:
      # Set IRIS instance IP Address
      - IRIS_HOST=172.16.238.20
      # Set IRIS instance port
      - IRIS_PORT=1972
      # Replace by the list of ip address allowed to open the CSP system manager
      # https://localhost/csp/bin/RunTime/Module.cxw
      - "SYSTEM_MANAGER=*.*.*.*"
      # the list of web apps
      # /csp allow to the webgateway to redirect all request starting by /csp to the iris instance
      # You can specify a list separate by a space : "IRIS_WEBAPPS=/csp /api /isc /swagger-ui"
      - "IRIS_WEBAPPS=/csp"
    volumes:
      # Mount certificates files.
      # - ~/webgateway-apache-certificates/webgateway_client.cer:/opt/webgateway/bin/webgateway_client.cer
      # - ~/webgateway-apache-certificates/webgateway_client.key:/opt/webgateway/bin/webgateway_client.key
      # - ~/webgateway-apache-certificates/CA_Server.cer:/opt/webgateway/bin/CA_Server.cer
      # - ~/webgateway-apache-certificates/apache_webgateway.cer:/etc/apache2/certificate/apache_webgateway.cer
      # - ~/webgateway-apache-certificates/apache_webgateway.key:/etc/apache2/certificate/apache_webgateway.key
    hostname: webgateway
    command: ["--ssl"]

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"